config/routes.rb
Rails.application.routes.draw do
  root "mains#index"
  resources :contacts, only: %i[new create]
  devise_for :users, only: %i[sessions registrations passwords]

  namespace :admin do
    resources :users
    resources :abouts
    resources :basics
    resources :logos
    resources :products
    resources :banners
    resources :contacts do
      member do
        patch :reply
      end
    end
    resources :users, only: %i[show], param: :username
    resources :sessions, only: [:new, :create, :destroy]
    get '/dashboard', to: 'dashboards#index', as: :dashboard
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  has_many :mains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord

  validates :title, presence: true
  has_one_attached :photo
end

app/models/basic.rb
class Basic < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord

  has_one_attached :logotype
end

app/models/main.rb
class Main < ApplicationRecord
  belongs_to :about
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :name, :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/admin/banners_controller.rb
module Admin
  class BannersController < ApplicationController
    before_action :set_banner, only: %i[ show edit update destroy ]

    # GET /banners or /banners.json
    def index
      @banners = Banner.all
    end

    # GET /banners/1 or /banners/1.json
    def show
    end

    # GET /banners/new
    def new
      @banner = Banner.new
    end

    # GET /banners/1/edit
    def edit
    end

    # POST /banners or /banners.json
    def create
      @banner = Banner.new(banner_params)

      respond_to do |format|
        if @banner.save
          format.html { redirect_to admin_banners_path, notice: "Banner was successfully created." }
          format.json { render :show, status: :created, location: @banner }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /banners/1 or /banners/1.json
    def update
      respond_to do |format|
        if @banner.update(banner_params)
          format.html { redirect_to admin_banners_path, notice: "Banner was successfully updated." }
          format.json { render :show, status: :ok, location: @banner }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /banners/1 or /banners/1.json
    def destroy
      @banner.destroy!

      respond_to do |format|
        format.html { redirect_to banners_path, status: :see_other, notice: "Banner was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_banner
        @banner = Banner.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def banner_params
        params.require(:banner).permit(:title, :description, :photo)
      end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < PublicController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contato enviado com sucesso." }
        format.html { render :new }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/mains_controller.rb
class MainsController < PublicController
  before_action :fetch_about
  before_action :fetch_banner
  before_action :fetch_product
  before_action :fetch_logo
  before_action :fetch_basic

  def index
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
  end

  private

  def fetch_about
    @abouts = About.all
  end

  def fetch_banner
    @banners = Banner.all
  end

  def fetch_product
    @products = Product.all
  end

  def fetch_logo
    @logos = Logo.all
  end

  def fetch_basic
    @basics = Basic.all
  end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path)
    File.open("app/assets/images/#{path}", "rb") { |file| raw(file.read) }
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/banners/_banner.html.erb
<div id="<%= dom_id banner %>" class="admin-container">
  <div class="content">
    <div class="title">Título</div>
    <div class="text"><%= banner.title %></div>
  </div>
  <div class="content">
    <div class="title">Descrição</div>
    <div class="text"><%= banner.description %></div>
  </div>
  <div class="content">
    <div class="title">Banner</div>
    <div class="text"><%= image_tag banner.photo %></div>
  </div>
</div>

app/views/admin/banners/_form.html.erb
<%= form_with(model: [:admin, banner]) do |form| %>
  <% if banner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
        <% banner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :photo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Salvar', class: 'btn btn-success'  %>
  </div>
<% end %>

app/views/admin/banners/edit.html.erb
<% content_for :title, "Editing banner" %>

<h1>Editar Banner</h1>

<%= render "form", banner: @banner %>

<br>

<div>
  <%#= link_to "Show this banner", admin_banner_path(@banner) %>
  <%= link_to "Voltar", admin_banners_path %>
</div>

app/views/admin/banners/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Banners" %>

<h1>Banner</h1>

<div id="banners">
  <% @banners.each do |banner| %>
  <% if banner.title.blank? %>
    <%= link_to "Novo Banner", new_admin_banner_path, class: 'btn btn-primary' %>
  <% else %>
    <%= link_to "Editar Banner", edit_admin_banner_path(banner), class: 'btn btn-primary' %>
  <% end %>
    <%= render banner %>
  <% end %>
</div>

app/views/admin/banners/new.html.erb
<% content_for :title, "New banner" %>

<h1>New banner</h1>

<%= render "form", banner: @banner %>

<br>

<div>
  <%= link_to "Back to banners", banners_path %>
</div>

app/views/admin/banners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @banner %>

<div>
  <%= link_to "Edit this banner", edit_banner_path(@banner) %> |
  <%= link_to "Back to banners", banners_path %>

  <%= button_to "Destroy this banner", @banner, method: :delete %>
</div>