config/routes.rb
Rails.application.routes.draw do
  root "mains#index"
  resources :contacts, only: %i[new create]
  devise_for :users, only: %i[sessions registrations passwords]

  namespace :admin do
    resources :users
    resources :abouts
    resources :basics
    resources :logos
    resources :products
    resources :banners
    resources :contacts do
      member do
        patch :reply
      end
    end
    resources :users, only: %i[show], param: :username
    resources :sessions, only: [:new, :create, :destroy]
    get '/dashboard', to: 'dashboards#index', as: :dashboard
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  has_many :mains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord

  validates :title, presence: true
  has_one_attached :photo
end

app/models/basic.rb
class Basic < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord

  has_one_attached :logotype
end

app/models/main.rb
class Main < ApplicationRecord
  belongs_to :about
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :name, :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/admin/abouts_controller.rb
module Admin
  class AboutsController < ApplicationController
    before_action :set_about, only: %i[ show edit update destroy ]

    # GET /abouts or /abouts.json
    def index
      @abouts = About.all
    end

    # GET /abouts/1 or /abouts/1.json
    def show
    end

    # GET /abouts/new
    def new
      @about = About.new
    end

    # GET /abouts/1/edit
    def edit
    end

    # POST /abouts or /abouts.json
    def create
      @about = About.new(about_params)

      respond_to do |format|
        if @about.save
          format.html { redirect_to admin_abouts_path, notice: "About was successfully created." }
          format.json { render :show, status: :created, location: @about }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @about.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /abouts/1 or /abouts/1.json
    def update
      respond_to do |format|
        if @about.update(about_params)
          format.html { redirect_to admin_abouts_path, notice: "About was successfully updated." }
          format.json { render :show, status: :ok, location: @about }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @about.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /abouts/1 or /abouts/1.json
    def destroy
      @about.destroy!

      respond_to do |format|
        format.html { redirect_to abouts_path, status: :see_other, notice: "About was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_about
        @about = About.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def about_params
        params.require(:about).permit(:mission, :vision, :values, :aboutus)
      end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < PublicController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contato enviado com sucesso." }
        format.html { render :new }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/mains_controller.rb
class MainsController < PublicController
  before_action :fetch_about
  before_action :fetch_banner
  before_action :fetch_product
  before_action :fetch_logo
  before_action :fetch_basic

  def index
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
  end

  private

  def fetch_about
    @abouts = About.all
  end

  def fetch_banner
    @banners = Banner.all
  end

  def fetch_product
    @products = Product.all
  end

  def fetch_logo
    @logos = Logo.all
  end

  def fetch_basic
    @basics = Basic.all
  end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path)
    File.open("app/assets/images/#{path}", "rb") { |file| raw(file.read) }
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/abouts/_about.html.erb
<div id="<%= dom_id about %>" class="admin-container">
  <div class="content">
    <div class="title">Sobre Nós</div>
    <div class="text"><%= about.aboutus.to_s.html_safe %></div>
  </div>
  <div class="content">
    <div class="title">Missão</div>
    <div class="text"><%= about.mission.to_s.html_safe %></div>
  </div>
  <div class="content">
    <div class="title">Visão</div>
    <div class="text"><%= about.vision.to_s.html_safe %></div>
  </div>
  <div class="content">
    <div class="title">Valores</div>
    <div class="text"><%= about.values.to_s.html_safe %></div>
  </div>
</div>

app/views/admin/abouts/_form.html.erb
<%= form_with(model: [:admin, about]) do |form| %>
  <% if about.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :aboutus, style: "display: block" %>
    <%= form.rich_text_area :aboutus, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :mission, style: "display: block" %>
    <%= form.rich_text_area :mission, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :vision, style: "display: block" %>
    <%= form.rich_text_area :vision, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :values, style: "display: block" %>
    <%= form.rich_text_area :values, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/abouts/edit.html.erb
<% content_for :title, "Editing about" %>

<h1>Editar sobre nós</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%#= link_to "Show this about", admin_about_path(@about) %>
  <%= link_to "Voltar", admin_abouts_path %>
</div>

app/views/admin/abouts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Abouts" %>

<h1>Sobre nós</h1>

<div id="abouts">
  <% @abouts.each do |about| %>
    <% if about.aboutus.blank? %>
      <%= link_to "Novo Sobre nós", new_admin_about_path, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to "Editar Sobre nós", edit_admin_about_path(about), class: 'btn btn-primary' %>
    <% end %>
    <%= render about %>
  <% end %>
</div>

app/views/admin/abouts/new.html.erb
<% content_for :title, "New about" %>

<h1>New about</h1>

<%= render "form", about: @about %>

<br>

<div>
  <%= link_to "Back to abouts", abouts_path %>
</div>

app/views/admin/abouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @about %>

<div>
  <%= link_to "Edit this about", edit_about_path(@about) %> |
  <%= link_to "Back to abouts", abouts_path %>

  <%= button_to "Destroy this about", @about, method: :delete %>
</div>