config/routes.rb
Rails.application.routes.draw do
  root "mains#index"
  resources :contacts, only: %i[new create]
  devise_for :users, only: %i[sessions registrations passwords]

  namespace :admin do
    resources :users
    resources :abouts
    resources :basics
    resources :logos
    resources :products
    resources :banners
    resources :contacts do
      member do
        patch :reply
      end
    end
    resources :users, only: %i[show], param: :username
    resources :sessions, only: [:new, :create, :destroy]
    get '/dashboard', to: 'dashboards#index', as: :dashboard
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  has_many :mains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord

  validates :title, presence: true
  has_one_attached :photo
end

app/models/basic.rb
class Basic < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord

  has_one_attached :logotype
end

app/models/main.rb
class Main < ApplicationRecord
  belongs_to :about
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :name, :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]

    # GET /products or /products.json
    def index
      @products = Product.all
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_path, notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_path, notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy!

      respond_to do |format|
        format.html { redirect_to admin_products_path, status: :see_other, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:name, :description, :image)
      end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < PublicController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contato enviado com sucesso." }
        format.html { render :new }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/mains_controller.rb
class MainsController < PublicController
  before_action :fetch_about
  before_action :fetch_banner
  before_action :fetch_product
  before_action :fetch_logo
  before_action :fetch_basic

  def index
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
  end

  private

  def fetch_about
    @abouts = About.all
  end

  def fetch_banner
    @banners = Banner.all
  end

  def fetch_product
    @products = Product.all
  end

  def fetch_logo
    @logos = Logo.all
  end

  def fetch_basic
    @basics = Basic.all
  end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path)
    File.open("app/assets/images/#{path}", "rb") { |file| raw(file.read) }
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product]) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr id="<%= dom_id product %>">
  <th scope="row"><%= product.id %></th>
  <td>
    <% if product.image.attached? %>
      <%= image_tag product.image %>
    <% end %>
  </td>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td style="display: flex; gap: 10px;">
    <%= link_to admin_product_path(product), class: "btn btn-primary", data: { bs_toggle: "modal", bs_target: "#exampleModal#{product.id}" } do %>
      <i class="bi bi-envelope-fill"></i> Visualizar Produto
    <% end %>
    <%= button_to "Deletar", admin_product_path(product), method: :delete, class: "btn btn-danger" %>
  </td>
</tr>


<!-- Modal -->
<div class="modal fade" id="exampleModal<%= product.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= product.name %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Id: <%= product.id %></p>
        <% if product.image.attached? %>
          <%= image_tag product.image %>
        <% end %>
        <p>Nome: <%= product.name %></p>
        <p>Descrição: <%= product.description %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editar Produto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", admin_product_path(@product) %> |
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Produtos</h1>

<%= link_to "Novo Produto", new_admin_product_path, class: 'btn btn-primary' %>


<table class="table table-hover table-product">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"></th>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<% content_for :title, "New product" %>

<h1>Novo Produto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Voltar", admin_products_path %>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>