config/routes.rb
Rails.application.routes.draw do
  root "mains#index"
  resources :contacts, only: %i[new create]
  devise_for :users, only: %i[sessions registrations passwords]

  namespace :admin do
    resources :users
    resources :abouts
    resources :basics
    resources :logos
    resources :products
    resources :banners
    resources :contacts do
      member do
        patch :reply
      end
    end
    resources :users, only: %i[show], param: :username
    resources :sessions, only: [:new, :create, :destroy]
    get '/dashboard', to: 'dashboards#index', as: :dashboard
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/about.rb
class About < ApplicationRecord
  has_many :mains
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/banner.rb
class Banner < ApplicationRecord

  validates :title, presence: true
  has_one_attached :photo
end

app/models/basic.rb
class Basic < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/logo.rb
class Logo < ApplicationRecord

  has_one_attached :logotype
end

app/models/main.rb
class Main < ApplicationRecord
  belongs_to :about
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :name, :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/admin/logos_controller.rb
module Admin
  class LogosController < ApplicationController
    before_action :set_logo, only: %i[ show edit update destroy ]

    # GET /logos or /logos.json
    def index
      @logos = Logo.all
    end

    # GET /logos/1 or /logos/1.json
    def show
    end

    # GET /logos/new
    def new
      @logo = Logo.new
    end

    # GET /logos/1/edit
    def edit
    end

    # POST /logos or /logos.json
    def create
      @logo = Logo.new(logo_params)

      respond_to do |format|
        if @logo.save
          format.html { redirect_to admin_logos_path, notice: "Logo was successfully created." }
          format.json { render :show, status: :created, location: @logo }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @logo.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /logos/1 or /logos/1.json
    def update
      respond_to do |format|
        if @logo.update(logo_params)
          format.html { redirect_to admin_logos_path, notice: "Logo was successfully updated." }
          format.json { render :show, status: :ok, location: @logo }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @logo.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /logos/1 or /logos/1.json
    def destroy
      @logo.destroy!

      respond_to do |format|
        format.html { redirect_to logos_path, status: :see_other, notice: "Logo was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_logo
        @logo = Logo.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def logo_params
        params.require(:logo).permit(:name, :logotype)
      end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < PublicController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contato enviado com sucesso." }
        format.html { render :new }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/mains_controller.rb
class MainsController < PublicController
  before_action :fetch_about
  before_action :fetch_banner
  before_action :fetch_product
  before_action :fetch_logo
  before_action :fetch_basic

  def index
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
  end

  private

  def fetch_about
    @abouts = About.all
  end

  def fetch_banner
    @banners = Banner.all
  end

  def fetch_product
    @products = Product.all
  end

  def fetch_logo
    @logos = Logo.all
  end

  def fetch_basic
    @basics = Basic.all
  end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path)
    File.open("app/assets/images/#{path}", "rb") { |file| raw(file.read) }
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/logos/_form.html.erb
<%= form_with(model: [:admin, logo]) do |form| %>
  <% if logo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
        <% logo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :logotype, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/logos/_logo.html.erb
<div id="<%= dom_id logo %>" class="admin-container">
  <div class="content">
    <div class="title">Nome</div>
    <div class="text"><%= logo.name %></div>
  </div>
  <div class="content">
    <div class="title">Logo</div>
    <div class="text logo">
      <% if logo.logotype.attached? %>
        <%= image_tag logo.logotype %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/logos/edit.html.erb
<% content_for :title, "Editing logo" %>

<h1>Editar Logo</h1>

<%= render "form", logo: @logo %>

<br>

<div>
  <%#= link_to "Show this logo", admin_logo_path(@logo) %>
  <%= link_to "Voltar", admin_logos_path %>
</div>

app/views/admin/logos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Logos" %>

<h1>Logos</h1>

<div id="logos">
  <% @logos.each do |logo| %>
    <% if logo.name.blank? %>
      <%= link_to "Novo Logo", new_admin_logo_path, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to "Editar Logo", edit_admin_logo_path(logo), class: 'btn btn-primary' %>
    <% end %>
    <%= render logo %>
  <% end %>
</div>

app/views/admin/logos/new.html.erb
<% content_for :title, "New logo" %>

<h1>New logo</h1>

<%= render "form", logo: @logo %>

<br>

<div>
  <%= link_to "Back to logos", logos_path %>
</div>

app/views/admin/logos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @logo %>

<div>
  <%= link_to "Edit this logo", edit_logo_path(@logo) %> |
  <%= link_to "Back to logos", logos_path %>

  <%= button_to "Destroy this logo", @logo, method: :delete %>
</div>